version: '3'
services:
  zookeeper:
    image: jplock/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: ches/kafka
    ports:
      - "9092:9092"
      - "7203:7203"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    environment:
      ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
  producer:
    build: producer
    ports:
     - "9000:9000"
    links:
      - kafka
    depends_on:
      - kafka
  consumer:
    build: consumer
    ports:
      - "9001:9001"
    links:
      - kafka
    depends_on:
      - kafka